In [2]:
import numpy as np
import pandas as pd

np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
np.linspace(1,10,5) #start element,end element, number of elements

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [3]:
np.diag((2,1,4,6)) #diagonal

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [48]:
arr = np.random.rand(10,2,3)
arr

array([[[0.72760898, 0.37773542, 0.21587919],
        [0.10619606, 0.86785538, 0.14657104]],

       [[0.78817517, 0.33969025, 0.87437814],
        [0.79357594, 0.92575487, 0.16610717]],

       [[0.7505046 , 0.73694772, 0.26733308],
        [0.7698085 , 0.91570923, 0.75030538]],

       [[0.02794338, 0.01556802, 0.2892021 ],
        [0.64333096, 0.26394294, 0.43452994]],

       [[0.03491628, 0.01833211, 0.79835858],
        [0.05311952, 0.48253295, 0.82516297]],

       [[0.83368838, 0.80311997, 0.69484761],
        [0.54794749, 0.69769023, 0.0562042 ]],

       [[0.36687048, 0.3019167 , 0.13037203],
        [0.89273106, 0.72865006, 0.79315365]],

       [[0.8056068 , 0.4770178 , 0.55060785],
        [0.77534176, 0.61410329, 0.79920866]],

       [[0.55513444, 0.16656163, 0.24224501],
        [0.75164884, 0.263963  , 0.35206989]],

       [[0.09763656, 0.21678071, 0.61314327],
        [0.61572493, 0.22503979, 0.27847023]]])

In [21]:
arr.dtype

dtype('float64')

In [28]:
arr.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [4]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]);
ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [5]:
ar[2,:] #row 3

array([11, 12, 13])

In [6]:
ar[:,0] #column 1

array([ 2,  9, 11])

In [51]:
ar.size

9

In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.random.randint(10, size=(2,10,3))

array([[[7, 0, 3],
        [2, 7, 2],
        [5, 2, 7],
        [4, 4, 2],
        [7, 9, 5],
        [7, 5, 9],
        [5, 3, 1],
        [4, 9, 8],
        [9, 4, 3],
        [8, 0, 9]],

       [[8, 4, 8],
        [7, 7, 7],
        [6, 1, 4],
        [1, 7, 6],
        [4, 1, 1],
        [2, 2, 0],
        [1, 2, 4],
        [7, 5, 4],
        [7, 0, 7],
        [2, 2, 3]]])

In [55]:
arr1 = np.arange(100)
arr1.shape = (5,20)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [72]:
arr1[[1,2,1],[1,2,2]] = 111 #override values
arr1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20, 111, 111,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41, 111,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99]])

In [77]:
ar = np.random.randint(10, size=(2,10))
evenMask = (ar % 2 ==0)
evenNum = ar[evenMask]

evenNum

array([0, 6, 2, 4, 4, 4])

In [78]:
x = ar.copy()
x

array([[5, 3, 5, 7, 7, 9, 3, 1, 0, 6],
       [2, 4, 4, 9, 1, 4, 5, 7, 9, 1]])

In [108]:
x1 = np.array([np.arange(0,11), np.arange(11,22)]);
x2 = x1.ravel();
x3 = x1.T.ravel(); x3


array([ 0, 11,  1, 12,  2, 13,  3, 14,  4, 15,  5, 16,  6, 17,  7, 18,  8,
       19,  9, 20, 10, 21])

In [123]:
x4 = np.arange(1,21); x4
x4.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [5]:
x = np.arange(10)
x.resize(12); x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0])

In [19]:
dates = pd.date_range('20190101',periods=12,freq='M'); dates

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31'],
              dtype='datetime64[ns]', freq='M')

In [15]:
np.random.randint(1,20,(12,10))

array([[16,  1,  6,  6, 17, 13, 16, 15, 13, 19],
       [ 6, 12,  3, 15, 10, 19,  6,  9,  4,  3],
       [19, 14,  6,  1,  6, 12,  6, 13,  2, 19],
       [11, 14, 16, 13, 16,  7,  9, 13,  6, 18],
       [ 3, 17, 11,  3, 17,  1, 11, 10,  5, 18],
       [ 9, 13,  4,  4, 15, 10, 19, 10, 18,  3],
       [ 3, 12, 15,  2, 18,  8, 17, 13,  5,  8],
       [ 9, 12, 15, 17, 11,  7,  4, 14,  3, 18],
       [18, 11,  2,  1, 11, 19, 18, 16, 19, 16],
       [ 1,  9, 14,  9,  6,  1, 11, 18,  1, 14],
       [ 8, 12, 18, 13,  9, 16,  1,  4, 14, 11],
       [ 9, 13,  2,  2,  7,  9, 15,  2,  5, 19]])

In [25]:
df = pd.DataFrame(np.random.randint(1,20,(12,10)), index = dates, columns=list('ABCDEFGHJK'))

In [32]:
#df.index
#df.values
df.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K'], dtype='object')

In [33]:
df.T #transposing

2019-01-31  2019-02-28  2019-03-31  2019-04-30  2019-05-31  2019-06-30  \
A          18           8           6           2           1          14   
B           6          13           7           2          13          18   
C          17           8           3           9           1          11   
D           8          12           5           6          13           8   
E           3           3          11           2           5           8   
F          16          16           7          19           7          14   
G          10           9          14           6          15           7   
H           1          19          10           4           6          14   
J          10           2          14          14           4          11   
K          15          13          19          16          16          10   

   2019-07-31  2019-08-31  2019-09-30  2019-10-31  2019-11-30  2019-12-31  
A          10           5          14          11          12          11  
B           7           9           6          18           7          13  
C          12          18          16           6           2          11  
D          19           4           5           6          11          16  
E          13          13           5          16           8           9  
F          13          14           3           3          13           3  
G           9           5          15           9          10           8  
H          18           8           3           7           6          16  
J          14           2           7          17           7          11  
K           4           2          17           6           8          17

In [35]:
df.sort_index(axis=1, ascending=False)

K   J   H   G   F   E   D   C   B   A
2019-01-31  15  10   1  10  16   3   8  17   6  18
2019-02-28  13   2  19   9  16   3  12   8  13   8
2019-03-31  19  14  10  14   7  11   5   3   7   6
2019-04-30  16  14   4   6  19   2   6   9   2   2
2019-05-31  16   4   6  15   7   5  13   1  13   1
2019-06-30  10  11  14   7  14   8   8  11  18  14
2019-07-31   4  14  18   9  13  13  19  12   7  10
2019-08-31   2   2   8   5  14  13   4  18   9   5
2019-09-30  17   7   3  15   3   5   5  16   6  14
2019-10-31   6  17   7   9   3  16   6   6  18  11
2019-11-30   8   7   6  10  13   8  11   2   7  12
2019-12-31  17  11  16   8   3   9  16  11  13  11

In [42]:
df.sort_values(by='B', ascending=False)

A   B   C   D   E   F   G   H   J   K
2019-06-30  14  18  11   8   8  14   7  14  11  10
2019-10-31  11  18   6   6  16   3   9   7  17   6
2019-02-28   8  13   8  12   3  16   9  19   2  13
2019-05-31   1  13   1  13   5   7  15   6   4  16
2019-12-31  11  13  11  16   9   3   8  16  11  17
2019-08-31   5   9  18   4  13  14   5   8   2   2
2019-03-31   6   7   3   5  11   7  14  10  14  19
2019-07-31  10   7  12  19  13  13   9  18  14   4
2019-11-30  12   7   2  11   8  13  10   6   7   8
2019-01-31  18   6  17   8   3  16  10   1  10  15
2019-09-30  14   6  16   5   5   3  15   3   7  17
2019-04-30   2   2   9   6   2  19   6   4  14  16

In [46]:
df.iloc[0:5,0:6]

A  B   C   D   E   F
2019-04-30   2  2   9   6   2  19
2019-01-31  18  6  17   8   3  16
2019-09-30  14  6  16   5   5   3
2019-03-31   6  7   3   5  11   7
2019-07-31  10  7  12  19  13  13

In [53]:
df.max(1)

2019-04-30    19
2019-01-31    18
2019-09-30    17
2019-03-31    19
2019-07-31    19
2019-11-30    13
2019-08-31    18
2019-02-28    19
2019-05-31    16
2019-12-31    17
2019-06-30    18
2019-10-31    18
dtype: int64

In [58]:
df1 = pd.DataFrame(np.random.randn(10,4))
pieces = [df1[:3],df1[3:7],df1[7:]]
pieces

[          0         1         2         3
 0 -0.172442 -0.947747 -1.316230 -0.589092
 1 -0.532462 -0.397806 -0.305503  1.378150
 2 -0.932177  0.693643 -0.789094  0.337584,
           0         1         2         3
 3  0.390823  0.222864 -0.104725  0.501594
 4  0.489345 -0.041561  0.413530  1.392427
 5  0.181830 -1.351505  1.359543  1.125239
 6  2.374853  0.173722  0.078972 -0.970820,
           0         1         2         3
 7  0.511425  0.460987  0.367134 -0.955197
 8  0.719448 -1.581259 -2.362411 -0.719053
 9 -0.958560 -1.396035 -0.654628  1.722517]

In [61]:
gluepieces = pd.concat(pieces); gluepieces

0         1         2         3
0 -0.172442 -0.947747 -1.316230 -0.589092
1 -0.532462 -0.397806 -0.305503  1.378150
2 -0.932177  0.693643 -0.789094  0.337584
3  0.390823  0.222864 -0.104725  0.501594
4  0.489345 -0.041561  0.413530  1.392427
5  0.181830 -1.351505  1.359543  1.125239
6  2.374853  0.173722  0.078972 -0.970820
7  0.511425  0.460987  0.367134 -0.955197
8  0.719448 -1.581259 -2.362411 -0.719053
9 -0.958560 -1.396035 -0.654628  1.722517

In [68]:
dfx1 = pd.DataFrame({'key1':['a','b','c','d','e'],'values':['1','2','3','4','5']}); dfx1

key1 values
0    a      1
1    b      2
2    c      3
3    d      4
4    e      5

In [69]:
dfx2 = pd.DataFrame({'key1':['a','b','c','d','e'],'values':['6','7','8','9','10']}); dfx2

key1 values
0    a      6
1    b      7
2    c      8
3    d      9
4    e     10

In [70]:
pd.merge(dfx1,dfx2,on='key1')

key1 values_x values_y
0    a        1        6
1    b        2        7
2    c        3        8
3    d        4        9
4    e        5       10