In [2]:
import numpy as np

In [ ]:
np.random??

In [75]:
a2 = np.arange(10)
a2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [45]:
lst=[]
for q in range(50,1050,100):
    lst.append(q)
    
for i in range(len(lst)):
    print(lst[i])

50
150
250
350
450
550
650
750
850
950


In [121]:
np.linspace(10,100,9, endpoint=True, retstep=True)

(array([ 10.  ,  21.25,  32.5 ,  43.75,  55.  ,  66.25,  77.5 ,  88.75,
        100.  ]), 11.25)

In [126]:
np.logspace(1.0, 5.0, num=50, endpoint=False)

array([1.00000000e+01, 1.20226443e+01, 1.44543977e+01, 1.73780083e+01,
       2.08929613e+01, 2.51188643e+01, 3.01995172e+01, 3.63078055e+01,
       4.36515832e+01, 5.24807460e+01, 6.30957344e+01, 7.58577575e+01,
       9.12010839e+01, 1.09647820e+02, 1.31825674e+02, 1.58489319e+02,
       1.90546072e+02, 2.29086765e+02, 2.75422870e+02, 3.31131121e+02,
       3.98107171e+02, 4.78630092e+02, 5.75439937e+02, 6.91830971e+02,
       8.31763771e+02, 1.00000000e+03, 1.20226443e+03, 1.44543977e+03,
       1.73780083e+03, 2.08929613e+03, 2.51188643e+03, 3.01995172e+03,
       3.63078055e+03, 4.36515832e+03, 5.24807460e+03, 6.30957344e+03,
       7.58577575e+03, 9.12010839e+03, 1.09647820e+04, 1.31825674e+04,
       1.58489319e+04, 1.90546072e+04, 2.29086765e+04, 2.75422870e+04,
       3.31131121e+04, 3.98107171e+04, 4.78630092e+04, 5.75439937e+04,
       6.91830971e+04, 8.31763771e+04])

In [101]:
x = np.arange(5,105,5).reshape(2,2,5);
x2 = np.asarray(x,dtype=float)


print(x);print('As int')
print('-'*100);
print(x2);print('As float')
print('-'*100);
print('Number of dimensions: ',x.ndim);
print('The size of item X is: ',x.itemsize, 'bytes');


[[[  5  10  15  20  25]
  [ 30  35  40  45  50]]

 [[ 55  60  65  70  75]
  [ 80  85  90  95 100]]]
As int
----------------------------------------------------------------------------------------------------
[[[  5.  10.  15.  20.  25.]
  [ 30.  35.  40.  45.  50.]]

 [[ 55.  60.  65.  70.  75.]
  [ 80.  85.  90.  95. 100.]]]
As float
----------------------------------------------------------------------------------------------------
Number of dimensions:  3
The size of item X is:  8 bytes


In [97]:
np.empty([2,10],dtype=int, order='C' ) #Return a new array of given shape and type, without initializing entries

array([[           21784048,     139976205552912,            10296512,
        6660032592998379568, 4265009324410024053,                 129,
            139976205402352,     139976205402352,                   0,
                         97],
       [    139976205402320,     139976205402320, 8390326387129478690,
        3196769774425811065, 2323048602843837540, 7287435672274890345,
        7957695015493526904, 4189038621173441375,             8206392,
                         -1]])

In [116]:
np.fromiter(range(20),dtype=int) #Create a new 1-dimensional array from an iterable object.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
a4 = np.arange(1,(100+1)).reshape(5,5,4);a4

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [150]:
a4[0:,2:,0]; #All from frist dim, from 3rd row till end all rows per dim, first column from all dim

----------------------------------------------------------------------------------------------------


array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38],
       [42, 46, 50, 54, 58],
       [62, 66, 70, 74, 78],
       [82, 86, 90, 94, 98]])

In [153]:
a4[...,1]; #items from each second column

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

In [155]:
a4[0,...] #items from each first row

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [165]:
x = np.array([[1, 2], [3, 4], [5, 6]])  
x[[0,1,2], [0,1,0]] #1st dimension 0,1,2 and 2nd dim 0,1,1

array([1, 4, 5])

In [184]:
x5 = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x5[rows,cols] 
y

array([[ 0,  2],
       [ 9, 11]])

In [188]:
x5[x5 % 2== 0]

array([ 0,  2,  4,  6,  8, 10])

In [10]:
#complex number is like 3*j or 3j

x6 = np.array([1, 2+6j, 5, 3.5+5j]);
print(x6);
print(np.iscomplex(x6));
print(x6[np.iscomplex(x6)]);

[1. +0.j 2. +6.j 5. +0.j 3.5+5.j]
[False  True False  True]
[2. +6.j 3.5+5.j]


In [45]:
#Broadcasting
print('Array with broadcasting')
print()
a6 = ((a4[0] + a4[1]) *2) + a4[3];
print(a6)
print()

print('Iterable array C-style order')
print()
for i in np.nditer(a6):
    print(i)
print()    

print('Iterable array F-style order')
print()
a6b = a6.copy(order='F')
for i2 in np.nditer(a6b):
    print(i2*5)
print()

print('Iterable modified array in F-style order')
print()
a6c = a6.copy(order = 'F')
for i3 in np.nditer(a6c, op_flags=['readwrite']):
    i3[...] = 2*i3
    print(i3)


Array with broadcasting

[[105 110 115 120]
 [125 130 135 140]
 [145 150 155 160]
 [165 170 175 180]
 [185 190 195 200]]

Iterable array C-style order

105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200

Iterable array F-style order

525
625
725
825
925
550
650
750
850
950
575
675
775
875
975
600
700
800
900
1000

Iterable modified array in F-style order

210
250
290
330
370
220
260
300
340
380
230
270
310
350
390
240
280
320
360
400


In [50]:
#Broadcasting with nditer
a6iter = [4,76,5,3]

for x,z in np.nditer([a6,a6iter]):
    print('%d:%d' % (x,z),)

105:4
110:76
115:5
120:3
125:4
130:76
135:5
140:3
145:4
150:76
155:5
160:3
165:4
170:76
175:5
180:3
185:4
190:76
195:5
200:3


In [64]:
#NumPy - Array Manipulation
print('Reshape')
print()
a4 = np.arange(1,(100+1)).reshape(5,5,4);
print(a4)
print()

print('Flatten')
print()
print(a4.flatten())
print()

print('Ravel F style sorting')
print()
print(a4.ravel(order = 'F'))
print()

print('Ravel C style sorting')
print()
print(a4.ravel(order = 'C'))
print()

print('Transpose')
print()
print(a4.T)
print()

print('Roll Axis')
print()
print(np.rollaxis(a4,2).shape)
print()



Reshape

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]
  [ 13  14  15  16]
  [ 17  18  19  20]]

 [[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]
  [ 33  34  35  36]
  [ 37  38  39  40]]

 [[ 41  42  43  44]
  [ 45  46  47  48]
  [ 49  50  51  52]
  [ 53  54  55  56]
  [ 57  58  59  60]]

 [[ 61  62  63  64]
  [ 65  66  67  68]
  [ 69  70  71  72]
  [ 73  74  75  76]
  [ 77  78  79  80]]

 [[ 81  82  83  84]
  [ 85  86  87  88]
  [ 89  90  91  92]
  [ 93  94  95  96]
  [ 97  98  99 100]]]

Flatten

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Ravel F style sorting

[  1  21  41  61  81   5  25  45  65  85

In [88]:
#Strides - moving rows
a = np.arange(10)
np.lib.stride_tricks.as_strided(a, shape = (7, 4), strides = a.strides * 2)[::2]

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [92]:
a = np.arange(20).reshape(5, 4)
print(a)

np.lib.stride_tricks.as_strided(a, shape = (15, 2, 2), strides = (8, 32, 8))[::2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[[ 0,  1],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [ 8,  9]],

       [[ 6,  7],
        [10, 11]],

       [[ 8,  9],
        [12, 13]],

       [[10, 11],
        [14, 15]],

       [[12, 13],
        [16, 17]],

       [[14, 15],
        [18, 19]]])

In [63]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [70]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[3 3 6 2 2 6 8 5 4 6]
[4 4 3 0 4 4 7 5 0 3]
[3 4 5]


In [72]:

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print('Today is: ',today, 'Yesterday was: ', yesterday, 'Tomorrow will be: ', tomorrow)

Today is:  2019-01-28 Yesterday was:  2019-01-27 Tomorrow will be:  2019-01-29


In [5]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [56]:
z1 = [0,1,0,3,0,5,0,7]
print('Non-zero elements of z1: ',np.nonzero(z1))

Non-zero elements of z1:  (array([1, 3, 5, 7]),)


In [6]:
np.ones((10,10),dtype=int,)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
x1 = np.arange(18).reshape((3, 6));
y1 = np.arange(12).reshape((2, 6));
print(x1)
print()
print(y1)
print()
print(np.concatenate((x1, y1), axis=0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [15]:
x2 = np.arange(18).reshape((3, 6));
y2 = np.arange(12).reshape((3, 4));
print(x2)
print()
print(y2)
print()
print(np.concatenate((x2, y2), axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3  4  5  0  1  2  3]
 [ 6  7  8  9 10 11  4  5  6  7]
 [12 13 14 15 16 17  8  9 10 11]]


In [22]:
print('Vstack, same number of columns')
print(np.vstack((x1,y1)))
print()
print('Hstack, same number of rows')
print(np.hstack((x2,y2)))

Vstack, same number of columns
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Hstack, same number of rows
[[ 0  1  2  3  4  5  0  1  2  3]
 [ 6  7  8  9 10 11  4  5  6  7]
 [12 13 14 15 16 17  8  9 10 11]]


In [49]:
print('Random')
print(np.random.random((2,5)))
print(np.random.random(5))

print('Permutation')
print(np.random.permutation(10))
print(np.random.permutation(x1))

print('Shuffle')
x2= np.arange(10)
print(np.random.shuffle(x2))

print('Choice')
print(np.random.choice(x2))


Random
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01]
 [9.23385948e-02 1.86260211e-01 3.45560727e-01 3.96767474e-01
  5.38816734e-01]]
[0.41919451 0.6852195  0.20445225 0.87811744 0.02738759]
Permutation
[8 3 5 9 0 6 1 7 4 2]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
Shuffle
None
Choice
6
Seed
